### ISSUE TITLE
Approval For New Bomb Stories

### ISSUE THREAD

**Issue by DrakeLambert** [The-Grace-Bomb-Company/Grace-Bomb-App#7]
Today, if a bomb story is uploaded to the Google Sheet, it will be retuned by the bomb API. 

Requirements:

- We want to give the Grace Bomb team a checkbox column in the sheet that determines if the story TEXT will be returned by the API or not. The bomb should always be returned.
- When the bomb is added, notify the user that it's under approval for now, and will show up after approval.

**Comment by arkfen** [comment]
This was already implemented inside of feature #5... sorry about that.
